import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import "./globals.css";
import ReactQueryProvider from "@/components/Providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/context/AuthContext";

import { cookies } from "next/headers";

const fetchUserData = async (token: string | null) => {
  if (!token) return null;

  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/current`, {
      cache: "force-cache",
      headers: { Cookie: `catcare=${token}` },
    });

    return await res.json();
  } catch (error) {
    console.error("Failed to fetch user data:", error);
    return null;
  }
};

const openSans = Open_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("catcare")?.value || null;

  const userData = await fetchUserData(token);

  return (
    <ReactQueryProvider>
      <AuthProvider data={userData?.data}>
        <html lang="en">
          <body className={openSans.className}>
            {children}
            <Toaster theme="light" position="top-center" richColors />
          </body>
        </html>
      </AuthProvider>
    </ReactQueryProvider>
  );
}
